import Head from 'next/head'
import Nav from '../Nav';

function submit(e: any){
    if (typeof window !== "undefined") {
        let email = e.target[0].value;
        let pass = e.target[1].value;

        localStorage.setItem("email", email);
        localStorage.setItem("password", pass);
    }
}
function SignIn(){
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"></link>
            </Head>
            <Nav />
            <div className="flex flex-col items-center justify-center w-screen mt-40  ">
                <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" action="/" onSubmit={submit}>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="email">
                        Email
                        </label>
                        <input  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Email" />
                    </div>
                    <div className="mb-6">
                        <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password">
                        Password
                        </label>
                        <input className="shadow appearance-none w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="password" />
                        
                    </div>
                    <div className="flex items-center justify-between">
                        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        Sign In
                        </button>
                    </div>
                    
                </form>
            </div>    
        </div>
        
    );
}

export default SignIn;